### ISSUE TITLE
DashMqtt parametrization

### ISSUE THREAD

**Issue by lmzh123** [aegis1980/dash-mqtt#2]
Good evening,

I'm trying to parametrize DashMqtt options in order to **authenticate** with the MQTT broker and also change its **port**, but these parameters don't seem to be taken into account and the port keeps on pointing to the default one 8083.

`TEST_SERVER = 'broker.url'
PROTOCOL = 'mqtts'
TEST_SERVER_PORT = 8883
TEST_SERVER_PATH = 'mqtts'
MESSAGE_OUT_TOPIC = 'out_topic'
MESSAGE_IN_TOPIC = 'in_topic'
options = {"keepalive": 30,
           "username": 'username',
           "password": 'password',
           "port": 8883}

---->

dash_mqtt.DashMqtt(
        id='mqtt',
        broker_url=TEST_SERVER,
        protocol=PROTOCOL,
        broker_port=TEST_SERVER_PORT,
        broker_path=TEST_SERVER_PATH,
        options=options,
        topics=[MESSAGE_IN_TOPIC]
    )
` 

Could somebody give me a simple example of how to properly do this or show me what I'm doing wrong. Thanks in advance!

**Comment by aegis1980** [comment]
Hey, 
It's been a while since I worked on this (or used it), or dash for that matter - seems there have been a few changes to Dash. 

I tried the following - similar to your code (changing from port 8083 but omitting mqtts & auth details):
```
TEST_SERVER = 'broker.emqx.io'
TEST_SERVER_PORT = 8883
TEST_SERVER_PATH = 'mqtt'
MESSAGE_OUT_TOPIC = 'testtopic'
MESSAGE_IN_TOPIC = 'testtopic'
options = {
    "port": 8883
}

app = dash.Dash(__name__)

app.layout = html.Div([
    dash_mqtt.DashMqtt(
        id='mqtt',
        broker_url=TEST_SERVER,
        broker_port = TEST_SERVER_PORT,
        broker_path = TEST_SERVER_PATH,
        topics=[MESSAGE_IN_TOPIC]
    ),
    html.H1('MQTT echo'),
    html.P('MQTT echo server to ' + TEST_SERVER + ' on port ' + str(TEST_SERVER_PORT)),
    dcc.Input(
        id='message_to_send',
        placeholder='message to send',
        debounce = True),
    html.Button('Send',id='send'),
    html.Div(id='return_message')
])
```
I get an error log in the browser console:
```
ws.js:108 WebSocket connection to 'ws://broker.emqx.io:8883/mqtt' failed: 
``` 
This fails because EMQX uses 8083 for _mqtt over websockets._ But error means that message is sent on the correct 8883 port (contrary to what you are finding). 

How do you know port not changing in your implementation?

Other stuff:
1. I think (from memory) you do not need to define port in options AND in constructor. [This (line 41) is the logic in code](https://github.com/aegis1980/dash-mqtt/blob/main/src/lib/components/DashMqtt.react.js#:~:text=if%20(!broker_port)%7B,%7D) on how that is dealt with.  
2. I am a little wary you are using MQTTS and auth details. As per notes in [readme.md](https://github.com/aegis1980/dash-mqtt/readme.md) I never implemented or tested for HTTPS. Maybe that is the problem? Dunno.

Anyway. Would love to help - if I can.

**Comment by lmzh123** [comment]
Hey @aegis1980,

I could successfully change the port and for knowing so I simply checked out the network logs on console, to be honest I don't know why they weren't changing before. On the other hand I couldn't connect using mqtts and credentials, but I understand they're not supported yet. Anyway thanks a lot for your help!

**Comment by aegis1980** [comment]
Cool! Good luck! Hope library useful. 
Make a pull request if you make improvements eh?
